#!/bin/sh

export MACOSX_DEPLOYMENT_TARGET=10.13

build() {
  arch=$1
  make clean
  arch -$arch ./build-macosx &&
  arch -$arch make dosbox-x.app &&
  cp -r dosbox-x.app dosbox-x-$arch.app
}

build x86_64 &&
build arm64 &&
lipo -create dosbox-x-arm64.app/Contents/MacOS/DosBox dosbox-x-x86_64.app/Contents/MacOS/DosBox -output dosbox-x.app/Contents/MacOS/DosBox
